### ISSUE TITLE
Mechanism for advos to have their own pages/update their own profiles

### ISSUE THREAD

**Issue by mikebroberg** [ibm-watson-data-lab/ibm-watson-data-lab.github.io#10]
We'd have to change how Brad's team Cloudant database works, or create a new one.

**Comment by vabarbosa** [comment]
@bradnoble @mikebroberg the team profiles are in an older instance of the Simple Search Service. if we want to continue to incorporate the Simple Search Service, one option is to update the Simple Search Service instance to a recent version. this will enable new options in the Simple Search Service admin page which allows for editing of individual data. in addition, it will also expose new CRUD REST APIs for the Simple Search Service.

**Comment by vabarbosa** [comment]
a new Simple Search Service has been created and placed in the Dev-Advocates org in Bluemix (which should be accessible to the team). former team members have been removed. for the time being current team member should login to the Simple Search Service and update their profiles.

**Comment by vabarbosa** [comment]
advo profile page has been added and can be viewed by clicking on the advo name from the team page or by going directly to `/team/#/<username>` (where _username_ is the github username). it is only showing the info currently available in the Simple Search Service. no mechanism yet in place to update profile from the site. for the time being advo can login to the Simple Search Service to update their info.

**Comment by vabarbosa** [comment]
@mikebroberg @bradnoble i have update the site so team profiles can now be updated directly from the site without having to go to the Simple Search Service admin page. It is still using the Simple Search but just accessing its API to update records.

- sign in using IBM email: https://ibm-watson-data-lab.github.io/signin
- edit profile: https://ibm-watson-data-lab.github.io/profile
