### ISSUE TITLE
Index the contents of projects.yml to enable faceted search

### ISSUE THREAD

**Issue by bradnoble** [ibm-watson-data-lab/ibm-watson-data-lab.github.io#104]
As a user, I'd like to be able to winnow the projects by fields we store per project.

**Comment by bradnoble** [comment]
Note: in making this work for .yml, it would be ideal to preserve the Simple Search Service functionality that makes it possible to index spreadsheets.

**Comment by mikebroberg** [comment]
Yay Va! Thanks, man.
