### ISSUE TITLE
Search doesn't find records

### ISSUE THREAD

**Issue by lornajane** [ibm-watson-data-lab/ibm-watson-data-lab.github.io#11]
I was looking for http://ibm-cds-labs.github.io/open-data/ and when I typed "open data" into the search box, it didn't find it.  I expected that it would be able to find the page on this site about open data.

**Comment by vabarbosa** [comment]
the **Search** page is for articles/blogs that have been curated. while the **Projects** page allows you to search the repos.

searching for `open data` under **Projects** would return `http://ibm-cds-labs.github.io/open-data`

@bradnoble @mikebroberg this may be something we want to review and see how we can make the distinction a little more clear. one idea could be to rename **Search** to **Articles** and **Projects** to **Repos** or another possibility would to be to have a single search page that searches across both.

**Comment by vabarbosa** [comment]
the **Projects** page no longer contains search. the **Search** page exists and searches articles/blogs that have been curated. it still may be worthwhile to consider how best to clarify this search if not necessarily for repos

**Comment by mikebroberg** [comment]
Closing this since it has been added to the site. Only remaining issue is with faceting when generated from project tags, which is now outlined in #193
