### ISSUE TITLE
Add SETI as a featured collection under Partners + Data

### ISSUE THREAD

**Issue by bradnoble** [ibm-watson-data-lab/ibm-watson-data-lab.github.io#117]
We've done a lot of project work around SETI. We should collect it all under a featured collection that also features a short and sweet writeup, to lead people into the project work.

**Comment by bradnoble** [comment]
It also appears that the powerful and popular ibmos2spark library was a bi-product of this work, which should be highlighted.

**Comment by mikebroberg** [comment]
Addressed by #121 and #122
