### ISSUE TITLE
Add PeaceTech as a featured collection under Partners + Data

### ISSUE THREAD

**Issue by bradnoble** [ibm-watson-data-lab/ibm-watson-data-lab.github.io#120]
This work helped us evolve pixiedust, pixieapps, and the publishing of pixieapps via containers to servers.

**Comment by mikebroberg** [comment]
I was never close to this work. Is there a place I can read up on it? Thanks.

**Comment by isc-rsingh** [comment]
I also want to know how I can get smarter on this work

**Comment by mikebroberg** [comment]
There's nothing on GitHub about this work. (A few repos, but no descriptions.) We're going to have to talk to David about it.

**Comment by mikebroberg** [comment]
I'll schedule time with David to get this info.

**Comment by mikebroberg** [comment]
I'm talking to David about this on Jan. 9. Sorry. Got a little delayed by the snow storms.

**Comment by mikebroberg** [comment]
OK @bradnoble @DTAIEB this draft is ready to review in my branch: https://github.com/ibm-watson-data-lab/ibm-watson-data-lab.github.io/blob/brobes-test-3/_features/peacetech.md
