### ISSUE TITLE
provide a hidden help page for editors

### ISSUE THREAD

**Issue by bradnoble** [ibm-watson-data-lab/ibm-watson-data-lab.github.io#18]
Would make clear the connection between the permalink values in the frontmatter of _features and _strategies files, and how they connect projects to those areas of the site experience.

**Comment by vabarbosa** [comment]
@bradnoble @mikebroberg would this possibly be better placed in the repo's [wiki](https://github.com/ibm-watson-data-lab/ibm-watson-data-lab.github.io/wiki)
