### ISSUE TITLE
Update search with facets for dates; fix AND-ing of faceting from project tags

### ISSUE THREAD

**Issue by mikebroberg** [ibm-watson-data-lab/ibm-watson-data-lab.github.io#193]
Authors will use the "lead" field in a project. Date, I'm not sure if it's better to do by month and year? Or just by year? Assigning to @vabarbosa but for when he's back on March 12.

**Comment by vabarbosa** [comment]
author facets - https://github.com/ibm-watson-data-lab/ibm-watson-data-lab.github.io/commit/e7772617f9ea999a5f71efd506a613eb67a86ab0

**Comment by mikebroberg** [comment]
Va added sorting by date by default in #200 . Remaining work for this issue is to get AND-ing working properly from search tags (AND-ing facets works properly when clicking checkboxes in the the right rail) and to expose the facets for dates (year/month).
