### ISSUE TITLE
Project tags + search facets: incorrectly AND-ing search queries

### ISSUE THREAD

**Issue by mikebroberg** [ibm-watson-data-lab/ibm-watson-data-lab.github.io#198]
## Starting from tags

When initiating a faceted search by clicking on a project tag, the corresponding facet in the right rail updates correspondingly. This is expected and good!

a.
![Screen Shot 2018-03-02 at 4.55.47 PM.png](https://images.zenhubusercontent.com/58addf7c51aa2c3057752d75/002e1440-4dc8-4c11-9485-5a5fea69f416)

b.
![Screen Shot 2018-03-02 at 4.56.00 PM.png](https://images.zenhubusercontent.com/58addf7c51aa2c3057752d75/b899e8c1-c6b9-4657-af80-c2ecd0ffd4a9)

What doesn't work is trying to add an additional facet to further narrow down your search. Either by clicking another tag or by clicking a second facet in the right rail -- the projects page won't properly `AND` the search terms. Instead, it will issue a new query to the faceted search engine.

For instance, clicking on the grey "Slack" tag under "Making of a Smart Business Chatbot: Part 2" in screenshot b results in an entirely new search query for Slack (instead of a search for `tags:"Watson Conversation" AND tags:"Slack"`):

c.
![Screen Shot 2018-03-02 at 5.05.14 PM.png](https://images.zenhubusercontent.com/58addf7c51aa2c3057752d75/dd483980-9aca-4593-91a4-32486eefc669)

## Starting from facets in the right rail

Queries also do not `AND` if starting from the right rail, you choose a term that has a space in it. The only way to properly narrow down facets is to ONLY choose facets in the right rail that are one word.

**Comment by mikebroberg** [comment]
I'll investigate further while Va is out next week.

**Comment by vabarbosa** [comment]
fixed here: https://github.com/ibm-watson-data-lab/ibm-watson-data-lab.github.io/commit/2ed6f27cbf27b07780f943e117842c3128d702fb

**Comment by vabarbosa** [comment]
@mikebroberg please re-open if i missed any other scenario
