### ISSUE TITLE
Content for Working With Data (strategy)

### ISSUE THREAD

**Issue by bradnoble** [ibm-watson-data-lab/ibm-watson-data-lab.github.io#23]
Placeholder page: https://ibm-watson-data-lab.github.io/working-with-wdp

Words from Glynn, in another document:

> We build libraries and tools that the core platform development teams don't (because they have a different focus). We identify gaps in our offerings and produce material that can plug the holes. 
> 
> Examples of libraries and tools:
>     Pixiedust to help Notebook users visualise their data
>     Silverliing a first-time user's Cloudant library 
>     Envoy a tool to help manage multi-user Cloudant applications
> 
> Such code should be produced to a professional standard, with automated tests and excellent documentation as it is intended to be incorporated into others' projects.

**Comment by mmcelaney** [comment]
I made a card to add content for cloudant under this section. Issue #60

**Comment by mikebroberg** [comment]
We already have copy for the main working-with-wdp strategy page. I think we're reasonably happy with it. The bigger issue is getting copy that's more than "lorem ipsum" placeholder for its two current collections:

* https://ibm-watson-data-lab.github.io/loading-data
* https://ibm-watson-data-lab.github.io/simple-search

I'll get something temporary up there, but it would be good to get more on this soon. Thanks.
