### ISSUE TITLE
Content for Notebooks for Developers (strategy)

### ISSUE THREAD

**Issue by bradnoble** [ibm-watson-data-lab/ibm-watson-data-lab.github.io#24]
The work we've[1] done with PixieDust and PixieApps are testament to the fact that Notebooks are useful for more than just data scientists. Let's develop this idea.

Placeholder page: https://ibm-watson-data-lab.github.io/notebooks-for-developers

[Inspiration](https://medium.com/ibm-watson-data-lab/i-am-not-a-data-scientist-efe7ca6ceba2)?

[1] Assignees are not data scientists

**Comment by mikebroberg** [comment]
We currently have _something_ at least. Are we happy with it?
