### ISSUE TITLE
Content for Watson + Data (collection)

### ISSUE THREAD

**Issue by bradnoble** [ibm-watson-data-lab/ibm-watson-data-lab.github.io#45]
Something to develop the idea that Watson with Data is smarter than Watson alone.

https://ibm-watson-data-lab.github.io/watson-and-data

**Comment by mikebroberg** [comment]
Don't know why this was added to the backlog, but I just pinged Mark about it.

**Comment by mikebroberg** [comment]
I added a quick draft today. So something reasonable is there if anyone should find it.
