### ISSUE TITLE
OpenWhisk (Cloud Functions) + Data (collection)

### ISSUE THREAD

**Issue by bradnoble** [ibm-watson-data-lab/ibm-watson-data-lab.github.io#47]
Something that explains the value of OpenWhisk, especially w/r/t data and data problems. 

https://ibm-watson-data-lab.github.io/openwhisk-and-data

**Comment by lornajane** [comment]
Great minds! https://github.com/ibm-watson-data-lab/ibm-watson-data-lab.github.io/tree/openwhisk-and-data-featured-collection I'm not done yet but it's in progress ...
