### ISSUE TITLE
Update team search

### ISSUE THREAD

**Issue by mikebroberg** [ibm-watson-data-lab/ibm-watson-data-lab.github.io#5]
1. expose facets by default in left rail

2. if location data exists for city state for each advo, expose that facet too

3. future: consider how we would give each advocate their own page based on entry in team database. would likely require changes to javascript? (if this doesn't make sense talk to Brad.)

**Comment by vabarbosa** [comment]
@mikebroberg and @Jordan-George  
for (1) please review pr #8 (https://github.com/ibm-cds-labs/ibm-cds-labs.github.io/commit/6c88476e604603fe7057725e5a9f1a8d0e78b388)

**Comment by vabarbosa** [comment]
for (2)
- only a handful of have `Location` information
- locations are either `United States - East`, `United States - West`, or `UK`
- `Location` is not set as a faceted field

thus to resolve (2)
- we should probably have more advocates update/include his or her location
- we need to facet the location field (i.e., update the underlining Simple Search Service data or update the index manually in the Cloudant service)

**Comment by vabarbosa** [comment]
for (3), if i understand correctly, there are a couple possible approaches. will each page just show the same data collected in the team database or will additional/specific data (not stored in the db) about each advocate be shown?
