### ISSUE TITLE
Add projects drop-down to main nav

### ISSUE THREAD

**Issue by mikebroberg** [ibm-watson-data-lab/ibm-watson-data-lab.github.io#6]
See example at http://materializecss.com/navbar.html#navbar-dropdown

**Comment by mikebroberg** [comment]
Looks good to me! @vabarbosa can you please review Jordan's changes in her branch? Thank you!

**Comment by mikebroberg** [comment]
#7 is the associated PR

**Comment by vabarbosa** [comment]
@mikebroberg i have reviewed/approved @Jordan-George PR #7.
i added just one minor comment for it.

on a related note we may want to clean up the header.html. there
are 3 copies of the navigation list (`ul`). i believe we only need 2
(desktop, mobile) and could possibly do away with the one at the
top of the page (outside of the `nav` tag).
