### ISSUE TITLE
Customize sort order of featured collections on strategy pages

### ISSUE THREAD

**Issue by mikebroberg** [ibm-watson-data-lab/ibm-watson-data-lab.github.io#77]
As Bradley notes in his comments on the PR for his Offlien First strategy content: https://github.com/ibm-watson-data-lab/ibm-watson-data-lab.github.io/pull/28#issue-246421513

![screen shot 2017-09-14 at 3 12 57 pm](https://user-images.githubusercontent.com/3170980/30450275-37f10cf2-995f-11e7-8ed7-66f8cd6cf087.png)

**Comment by mikebroberg** [comment]
omg this was so easy to fix after reading the documentation. I simply added a field to the collection files ("position") and then tacked this last sort filter onto the end of the existing variable assignment in the strategy layout: `{% assign collections = site.features | where:"strategies",page.permalink | sort:"position" %}`

**Comment by mikebroberg** [comment]
@bradley-holt Here's what it looks like now in my branch:

![screen shot 2018-01-10 at 12 05 56 pm](https://user-images.githubusercontent.com/3170980/34785288-adde3e52-f5fe-11e7-9ca0-b92ec3f54fcf.png)

**Comment by bradley-holt** [comment]
LGTM
