### ISSUE TITLE
Implement a way to showcase items from projects.yml as "essentials" of a featured collection

### ISSUE THREAD

**Issue by bradnoble** [ibm-watson-data-lab/ibm-watson-data-lab.github.io#96]
Today, the list of projects on a featured collection is just ordered by most recent at the top, and projects that are essential are not obvious.

**Comment by mikebroberg** [comment]
This shouldn't be too hard now that I know my way around Liquid a little better. We should talk about how you want them featured though @bradnoble -- like, sorted at the top of the projects list? Some other kind of visual indicator like a color or a border or something?

**Comment by mikebroberg** [comment]
Following up on this, we already have this functionality by adding essentials to the frontmatter of the collection's Mardown, like so:

```
---
title:      Offline Camp
headline:   Building the Offline First community, one campfire at a time.
layout:     layout-featured-collection
permalink:  offline-camp
featured:   true
#img:        offline-camp-campfire.jpeg #offlinecamp-logo.jpg
#img-thumb:  offline-camp-campfire.jpeg #offlinecamp-logo-thumb.jpg
strategies: 
  - offline-first
position:	0
essentials:
  Offline Camp:  http://offlinefirst.org/camp/  
  Offline Camp on Medium: https://medium.com/offline-camp
  Offline Camp on YouTube: https://www.youtube.com/OfflineFirst
  Offline First: http://offlinefirst.org/
  Offline First Resources: https://medium.com/offline-camp/offline-first-resources-2acc5836e9d4
  Offline First Slack Team: http://offlinefirst.org/chat/
lead:       teri-chadbourne
---
```

**Comment by mikebroberg** [comment]
I added this feature to my brobes-test-3 branch. ^^ See the commit message above @bradnoble . Also added @terichadbourne to this issue because she recently requested the same functionality.
